site_name: Datastuff

nav:
    - Home:                         'index.md'
    - 'Projects':
      - 'Zürich traffic flows':     'projects/zurich-traffic-flows.md'
      - 'gdocs exporter':           'projects/gdocs-exporter.md'
    - 'About':
      - 'License':                  'about/license.md'
      - 'Me':                       'about/me.md'

theme:
    name: gitbook