site_name: Datastuff

repo_url: https://github.com/mo-jan/datastuff

nav:
    - Home: 'index.md'
    - 'Projects':
      - 'Zürich traffic flows': 'zurich-traffic-flows'
      - 'gdocs exporter': 'gdocs-exporter'
    - 'About':
      - 'License': 'license.md'
      - 'Me': 'me'

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust